"""empty message

Revision ID: 555882cf145f
Revises: ffdc0a98111c
Create Date: 2022-05-10 16:29:42.711080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555882cf145f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
