"""empty message

Revision ID: 4a4804e1d242
Revises: 710f440fe9ef
Create Date: 2022-07-05 15:42:24.460006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4804e1d242'
down_revision = '710f440fe9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vid_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_liked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('videosLikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videosLikes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='videosLikes_user_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='videosLikes_video_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'video_id', name='videosLikes_pkey')
    )
    op.drop_table('vid_likes')
    # ### end Alembic commands ###
