"""empty message

Revision ID: 119764346ef4
Revises: 383780b73119
Create Date: 2022-07-12 02:55:46.905452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119764346ef4'
down_revision = '383780b73119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'view_count')
    # ### end Alembic commands ###
