"""empty message

Revision ID: 710f440fe9ef
Revises: f69add6e9c02
Create Date: 2022-06-08 13:01:45.674343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710f440fe9ef'
down_revision = 'f69add6e9c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videosLikes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videosLikes')
    # ### end Alembic commands ###
