"""empty message

Revision ID: 8207c770f7a3
Revises: 5acd4e9678f8
Create Date: 2022-07-06 15:21:45.576270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8207c770f7a3'
down_revision = '5acd4e9678f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videosdislikes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videosdislikes')
    # ### end Alembic commands ###
