"""empty message

Revision ID: c3167a9239b6
Revises: 555882cf145f
Create Date: 2022-05-10 19:19:25.493893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3167a9239b6'
down_revision = '555882cf145f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('header', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'header')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
