"""empty message

Revision ID: 2b2d4cf19ba5
Revises: 70dd43884de4
Create Date: 2022-07-06 19:51:47.417779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2d4cf19ba5'
down_revision = '70dd43884de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Subscribers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('subscriber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriber_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriber_pkey')
    )
    op.drop_table('Subscribers')
    # ### end Alembic commands ###
